### ISSUE TITLE
POSTS never go to MYSTREAM anymore

### ISSUE THREAD

**Issue by falon3** [CMPUT404Group/CMPUT404-project-socialdistribution#19]
this is a problem

**Comment by vanbelle** [comment]
this is just because the myStream is being refactored to pull the posts from the api rather than just using the posts.objects.get stuff we were using before, so when you create posts on a local server they arent on the heroku account where the posts are being pulled from.

however this isnt working all that well because its just pulling the public posts from that server which isnt really what we want. Since all the other code is commented out ill switch it back and just comment out the new stuff for now.
